[workspace]
members = [
    "curve25519-dalek",
    "curve25519-dalek-derive",
    "ed25519",
    "ed25519-dalek",
    "signature",
    "ed25519-dalek-bip32",
    "x25519-dalek",
]
resolver = "2"

[profile.dev]
opt-level = 2

